package models

type Player struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
}

var PLayerList = []Player{
	{ID: 1, Name: "Sachin Tendulkar", Role: "Batsman"},
	{ID: 2, Name: "Don Bradman", Role: "Batsman"},
	{ID: 3, Name: "Viv Richards", Role: "Batsman"},
	{ID: 4, Name: "Brian Lara", Role: "Batsman"},
	{ID: 5, Name: "Ricky Ponting", Role: "Batsman"},
	{ID: 6, Name: "Jacques Kallis", Role: "All-rounder"},
	{ID: 7, Name: "Shane Warne", Role: "Bowler"},
	{ID: 8, Name: "Muttiah Muralitharan", Role: "Bowler"},
	{ID: 9, Name: "Wasim Akram", Role: "Bowler"},
	{ID: 10, Name: "Glenn McGrath", Role: "Bowler"},
	{ID: 11, Name: "Curtly Ambrose", Role: "Bowler"},
	{ID: 12, Name: "Malcolm Marshall", Role: "Bowler"},
	{ID: 13, Name: "Imran Khan", Role: "All-rounder"},
	{ID: 14, Name: "Ian Botham", Role: "All-rounder"},
	{ID: 15, Name: "Kapil Dev", Role: "All-rounder"},
	{ID: 16, Name: "Adam Gilchrist", Role: "Wicket-keeper"},
	{ID: 17, Name: "MS Dhoni", Role: "Wicket-keeper"},
	{ID: 18, Name: "Kumar Sangakkara", Role: "Wicket-keeper"},
	{ID: 19, Name: "Andy Flower", Role: "Wicket-keeper"},
	{ID: 20, Name: "Mark Boucher", Role: "Wicket-keeper"},
	{ID: 21, Name: "Sunil Gavaskar", Role: "Batsman"},
	{ID: 22, Name: "Gordon Greenidge", Role: "Batsman"},
	{ID: 23, Name: "Desmond Haynes", Role: "Batsman"},
	{ID: 24, Name: "Javed Miandad", Role: "Batsman"},
	{ID: 25, Name: "Inzamam-ul-Haq", Role: "Batsman"},
	{ID: 26, Name: "Steve Waugh", Role: "Batsman"},
	{ID: 27, Name: "Mark Waugh", Role: "Batsman"},
	{ID: 28, Name: "Allan Border", Role: "Batsman"},
	{ID: 29, Name: "David Gower", Role: "Batsman"},
	{ID: 30, Name: "Graham Gooch", Role: "Batsman"},
	{ID: 31, Name: "Geoff Boycott", Role: "Batsman"},
	{ID: 32, Name: "Ken Barrington", Role: "Batsman"},
	{ID: 33, Name: "Len Hutton", Role: "Batsman"},
	{ID: 34, Name: "Jack Hobbs", Role: "Batsman"},
	{ID: 35, Name: "Wally Hammond", Role: "All-rounder"},
	{ID: 36, Name: "Garfield Sobers", Role: "All-rounder"},
	{ID: 37, Name: "Keith Miller", Role: "All-rounder"},
	{ID: 38, Name: "Richie Benaud", Role: "All-rounder"},
	{ID: 39, Name: "Ray Lindwall", Role: "Bowler"},
	{ID: 40, Name: "Dennis Lillee", Role: "Bowler"},
	{ID: 41, Name: "Jeff Thomson", Role: "Bowler"},
	{ID: 42, Name: "Joel Garner", Role: "Bowler"},
	{ID: 43, Name: "Michael Holding", Role: "Bowler"},
	{ID: 44, Name: "Andy Roberts", Role: "Bowler"},
	{ID: 45, Name: "Colin Croft", Role: "Bowler"},
	{ID: 46, Name: "Fred Trueman", Role: "Bowler"},
	{ID: 47, Name: "Jim Laker", Role: "Bowler"},
	{ID: 48, Name: "Hedley Verity", Role: "Bowler"},
	{ID: 49, Name: "Clarrie Grimmett", Role: "Bowler"},
	{ID: 50, Name: "Bill O'Reilly", Role: "Bowler"},
	{ID: 51, Name: "Anil Kumble", Role: "Bowler"},
	{ID: 52, Name: "Harbhajan Singh", Role: "Bowler"},
	{ID: 53, Name: "Ravichandran Ashwin", Role: "All-rounder"},
	{ID: 54, Name: "Ravindra Jadeja", Role: "All-rounder"},
	{ID: 55, Name: "Virat Kohli", Role: "Batsman"},
	{ID: 56, Name: "Rohit Sharma", Role: "Batsman"},
	{ID: 57, Name: "Kane Williamson", Role: "Batsman"},
	{ID: 58, Name: "Steve Smith", Role: "Batsman"},
	{ID: 59, Name: "Joe Root", Role: "Batsman"},
	{ID: 60, Name: "Ben Stokes", Role: "All-rounder"},
	{ID: 61, Name: "Pat Cummins", Role: "Bowler"},
	{ID: 62, Name: "Mitchell Starc", Role: "Bowler"},
	{ID: 63, Name: "Josh Hazlewood", Role: "Bowler"},
	{ID: 64, Name: "Nathan Lyon", Role: "Bowler"},
	{ID: 65, Name: "James Anderson", Role: "Bowler"},
	{ID: 66, Name: "Stuart Broad", Role: "Bowler"},
	{ID: 67, Name: "Kagiso Rabada", Role: "Bowler"},
	{ID: 68, Name: "Dale Steyn", Role: "Bowler"},
	{ID: 69, Name: "Shaun Pollock", Role: "All-rounder"},
	{ID: 70, Name: "Lance Klusener", Role: "All-rounder"},
	{ID: 71, Name: "Hansie Cronje", Role: "All-rounder"},
	{ID: 72, Name: "Graeme Pollock", Role: "Batsman"},
	{ID: 73, Name: "Barry Richards", Role: "Batsman"},
	{ID: 74, Name: "Mike Procter", Role: "All-rounder"},
	{ID: 75, Name: "Clive Rice", Role: "All-rounder"},
	{ID: 76, Name: "Virender Sehwag", Role: "Batsman"},
	{ID: 77, Name: "Gautam Gambhir", Role: "Batsman"},
	{ID: 78, Name: "Yuvraj Singh", Role: "All-rounder"},
	{ID: 79, Name: "Zaheer Khan", Role: "Bowler"},
	{ID: 80, Name: "Jasprit Bumrah", Role: "Bowler"},
	{ID: 81, Name: "Mohammed Shami", Role: "Bowler"},
	{ID: 82, Name: "Bhuvneshwar Kumar", Role: "Bowler"},
	{ID: 83, Name: "Umesh Yadav", Role: "Bowler"},
	{ID: 84, Name: "Ishant Sharma", Role: "Bowler"},
	{ID: 85, Name: "Ajinkya Rahane", Role: "Batsman"},
	{ID: 86, Name: "Cheteshwar Pujara", Role: "Batsman"},
	{ID: 87, Name: "KL Rahul", Role: "Batsman"},
	{ID: 88, Name: "Shikhar Dhawan", Role: "Batsman"},
	{ID: 89, Name: "Hardik Pandya", Role: "All-rounder"},
	{ID: 90, Name: "Rishabh Pant", Role: "Wicket-keeper"},
	{ID: 91, Name: "Wriddhiman Saha", Role: "Wicket-keeper"},
	{ID: 92, Name: "Dinesh Karthik", Role: "Wicket-keeper"},
	{ID: 93, Name: "Parthiv Patel", Role: "Wicket-keeper"},
	{ID: 94, Name: "Suresh Raina", Role: "All-rounder"},
	{ID: 95, Name: "Irfan Pathan", Role: "All-rounder"},
	{ID: 96, Name: "Ashish Nehra", Role: "Bowler"},
	{ID: 97, Name: "Munaf Patel", Role: "Bowler"},
	{ID: 98, Name: "Sreesanth", Role: "Bowler"},
	{ID: 99, Name: "RP Singh", Role: "Bowler"},
	{ID: 100, Name: "Praveen Kumar", Role: "Bowler"},
}
